app = 'evo-brillant'
swap_size_mb = 128

[build]

[env]
  PORT = 8080
  SERVER_PORT = 8080
  HOST = "0.0.0.0"
  NODE_ENV = "production"
  SERVER_URL = "https://evo-brillant.fly.dev"

  AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES = true
  AUTHENTICATION_TYPE = "jwt"
  AUTHENTICATION_JWT_EXPIRES_IN = 3600
  CORS_ORIGIN = "*"

  DATABASE_ENABLED = true
  DATABASE_PROVIDER = "postgresql"
  DATABASE_CONNECTION_CLIENT_NAME = "evo"

  CACHE_REDIS_ENABLED = true

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512